/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.f_rpt_tickets;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.parser.ParseException;

/**
 *
 * @author jorge
 */
public class rpt_det_tickets extends javax.swing.JDialog {
    
    private final f_rpt_tickets tickets = new f_rpt_tickets();
    
    /**
     * Creates new form rpt
     * @param parent
     */
    public rpt_det_tickets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tickets.formatjTableDet(this.jTableDetTickets);
        this.jLabelIdTicket.setVisible(false);
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "Cancel");
        
        getRootPane().getActionMap().put("Cancel", new javax.swing.AbstractAction(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e)
            {
                close();
            }
        });
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
    }
    
    private void close(){
        this.dispose();
    }
    
    public void cargaDetalleTicket() {
        try {
            tickets.obtenerDetalleTicketsPorId(this.jTableDetTickets, this.jLabelIdTicket);
        } catch (IOException ex) {
            Logger.getLogger(rpt_tickets.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(rpt_tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelIdTicket = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetTickets = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex) {
                return false;
            }
        }
        ;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumeroTicket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMontoTicket = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMontoPremiado = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdTicket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabelIdTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 23));

        jTableDetTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Jugada", "id_sorteo", "Sorteo", "Apuesta (Bs)", "Premio (Bs)", "Pagado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDetTickets.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDetTickets);
        if (jTableDetTickets.getColumnModel().getColumnCount() > 0) {
            jTableDetTickets.getColumnModel().getColumn(0).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(1).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(2).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(3).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(4).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(5).setResizable(false);
            jTableDetTickets.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 706, -1));

        jPanel2.setBackground(new java.awt.Color(19, 127, 141));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 246, 13));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("# Ticket:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 12, -1, -1));

        jLabelNumeroTicket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumeroTicket.setForeground(new java.awt.Color(244, 246, 13));
        jPanel2.add(jLabelNumeroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 12, 60, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFecha.setForeground(java.awt.Color.white);
        jPanel2.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 171, 17));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Monto Ticket:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 12, 100, -1));

        jLabelMontoTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMontoTicket.setForeground(java.awt.Color.white);
        jPanel2.add(jLabelMontoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 123, 18));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Monto Premiado:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 12, 125, -1));

        jLabelMontoPremiado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMontoPremiado.setForeground(java.awt.Color.white);
        jPanel2.add(jLabelMontoPremiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 121, 18));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 700, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpt_det_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpt_det_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpt_det_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpt_det_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                rpt_det_tickets dialog = new rpt_det_tickets(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelFecha;
    public javax.swing.JLabel jLabelIdTicket;
    public javax.swing.JLabel jLabelMontoPremiado;
    public javax.swing.JLabel jLabelMontoTicket;
    public javax.swing.JLabel jLabelNumeroTicket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetTickets;
    // End of variables declaration//GEN-END:variables
}
